fix NoClassDefFoundError on guicey startup due to junit classes leak into core (#428)
(cherry picked from commit 7aba2a42378e72fa649177c9ef28c3fb11a585c0)